### ISSUE TITLE
[1.37.0] First lighting event doesn't seem to trigger

### ISSUE THREAD

**Issue by AndreasVanVooren** [Aeroluna/Heck#112]
**Describe the bug**
The first lighting event caused by Chroma doesn't seem trigger properly. This is observed with the [Everlasting Eternity map. (34e3b)](https://beatsaver.com/maps/34e3b)

**To Reproduce**
Launch [Everlasting Eternity (34e3b)](https://beatsaver.com/maps/34e3b) in 1.37.0+. Observe that the environment is lit blue, instead of being completely unlit as expected.

**Expected behavior**
The environment is cloaked in darkness as expected.

**Additional context**
* Comparison footage: https://streamable.com/us637e
* Log zip: [2024.07.14.15.50.41.log.gz](https://github.com/user-attachments/files/16228057/2024.07.14.15.50.41.log.gz)

**Comment by Aeroluna** [comment]
after testing, it appears this bug happens without any mods installed at all.
for now, the bug has been patched out in CJD, but it should probably fixed in the vanilla game instead
https://github.com/Aeroluna/CustomJSONData/commit/d6eef4ea88cf2898b39dc2d67a242c87dfb3ffdc

for more specifics in what is occurring, in `BeatmapDataLoaderVersion3.BeatmapDataLoader.GetBeatmapDataFromSaveData`, `flag3` being true will cause `InsertDefaultEvents` to not be called:
![image](https://github.com/user-attachments/assets/1382b736-49b4-4fe7-bef4-acbce2d577e9)
however, the same implementation in `BeatmapDataLoaderVersion2_6_0AndEarlier.BeatmapDataLoader` always runs `InsertDefaultEvents` when `defaultLightshowSaveData != null` (as is the case on older environments) and ignores `flag3`:
![image](https://github.com/user-attachments/assets/73ad2624-5f47-412b-bafb-0fa0c99535d2)
this causes v2 maps to incorrectly add the default blue lights
