### ISSUE TITLE
Unable to press play when Heck is installed

### ISSUE THREAD

**Issue by xXPerditorXx** [Aeroluna/Heck#84]
**Describe the bug**
If I only load the Heck Mod, I cannot press Play anymore, whether Offical Music nor Unoffical Music.

**To Reproduce**
1. Install the latest version of BeatSaber (1.29.0)
2. Install Heck from ModInstaller or from this Git repo.
3. Launch BeatSaber and try to play a song.

**Expected behavior**
That I can play the Music that is required to have NoodleExtension installed, but I can't because even withe NoodleExtension uninstalled, the problem still persists.

**Additional context**
[_latest.log](https://github.com/Aeroluna/Heck/files/11137247/_latest.log)

**Comment by Mawntee** [comment]
Currently mods have not been updated for game version 1.29
This issue comes from using an old incompatible version of Heck/Chroma/Noodle with the wrong version of the game. 

In this case, mods meant for 1.28 being used on 1.29. 

Please wait until things are properly updated for version 1.29, or use something like Legacy Launcher to play on 1.28
![image](https://user-images.githubusercontent.com/51247415/229512003-aec02c4b-de5d-46e3-9879-a12bf15b074a.png)


If you would like to stay on 1.29 to play the new music pack, please remove "Heck, CustomJSONData, Chroma, and NoodleExtensions" dll's from your plugins folder.
