### ISSUE TITLE
Screen is black in main menu on start up.

### ISSUE THREAD

**Issue by juney2008** [Aeroluna/Heck#90]
**Describe the bug**
So when I installed Heck, Noodle Extensions, and Chroma and started up the game, the game is stuck on a black screen and was not showing the main menu of the game.

**To Reproduce**
1. Have Beat Saber updated to 1.31.0
2. Download Heck, Noodle Extensions, and Chroma in Mod Assistant
3. Start up the game.

**Expected behavior**
Show the Main menu screen

**Additional context**
[2023.08.04.11.54.22.log](https://github.com/Aeroluna/Heck/files/12263002/2023.08.04.11.54.22.log)

**Comment by Mawntee** [comment]
How many other mods do you have in there that are not from ModAssistant? 

Looking at your log, all the Heck mods (Chroma/Noodle/Etc) seem up to date, however I know there isn't a release of "Saber Factory" out yet for 1.31 (all the errors in your log appear after SiraUtil tries to load Saber Factory FYI)
![image](https://github.com/Aeroluna/Heck/assets/51247415/e237c361-9cd6-42ad-9270-786aae450f8b)


Please try removing Saber Factory, and let us know if the issue is still happening.

**Comment by Aeroluna** [comment]
As pointed out by Mawntee, the error is caused by trying to load an old version of Saber Factory, in the future go to BSMG discord and go to #pc-help for installation support.

**Comment by juney2008** [comment]
Oh, Alright then. Thanks for letting me know.
