### ISSUE TITLE
360Fyer Generated Walls Errors

### ISSUE THREAD

**Issue by procedure1** [Aeroluna/Heck#94]
I apologize for having to ask you this. I am a novice programmer and I'm trying to resurrect the old 360Fyer plugin that I love so much. I tried to clone your Heck/Chroma repository and build the project myself but I couldn't get it to build unfortunately. The Manifest says it is for BS v1.31.0 but I get tons of errors in the project when I add dependencies from 1.31.0 (like missing methods etc). I was going to rebuild it and add some log statements to see if I could track down an error I'm getting.
360Fyer has an option to add generated walls into a map (purely for visual interest since 360 maps are so lacking typically in visual interest). The Wall Generator does many calculations but eventually ends with this simple statement to create a wall.
data.AddBeatmapObjectDataInOrder(new ObstacleData(wallTime, lineIndex...

The Beat Saber logs gives me tons errors, presumably for each wall that is generated. If I turn OFF the Wall Generator, I don't get any errors. All the errors are the same:
[ERROR @ 16:04:38 | Chroma] Could not parse custom data for object [ObstacleData] at [182.5].
[ERROR @ 16:04:38 | Chroma] System.InvalidCastException: Specified cast is not valid.
[ERROR @ 16:04:38 | Chroma]   at Chroma.CustomDataManager.DeserializeObjects (CustomJSONData.CustomBeatmap.CustomBeatmapData beatmapData, System.Collections.Generic.Dictionary`2[TKey,TValue] beatmapTracks, System.Collections.Generic.Dictionary`2[TKey,TValue] pointDefinitions, System.Collections.Generic.IReadOnlyList`1[T] beatmapObjectDatas) [0x00019] in C:\Users\Aeroluna\source\repos\Heck\Chroma\HeckImplementation\CustomDataManager.cs:143 

I love your mods and I don't want to waste your time on this if you don't think this matters. I don't see any problem in-game, just these log errors.
Thanks for all your great work!

**Comment by Aeroluna** [comment]
When building, you should target the `dev` branch. The build configurations ending with "Latest" are currently updated for v1.31.1 and the others are for v1.29.1

All the projects use https://github.com/Zingabopp/BeatSaberModdingTools for handling dependencies, which means you need to define the `$(BeatSaberDir)` using a `.csproj.user` file while should look like
```
<?xml version="1.0" encoding="utf-8"?>
<Project>
  <PropertyGroup>
    <BeatSaberDir>C:\Program Files (x86)\Steam\steamapps\common\Beat Saber</BeatSaberDir>
  </PropertyGroup>
</Project>
```

The exception is being thrown because you are directly creating an ObstacleData but my mods assume that CJD is automatically replacing it with its own [CustomObstacleData](https://github.com/Aeroluna/CustomJSONData/blob/master/CustomJSONData/CustomBeatmap/ObjectData/CustomObstacleData.cs) type.

Three ways to solve this:
Change 360fyer to create the CJD type instead when its installed
Change my mods to check the type before casting
Have CJD automatically convert the type to the CJD type when calling AddBeatmapObjectDataInOrder (probably the best)

**Comment by procedure1** [comment]
Thanks so much for your prompt response and for the additional information about setting up references was super helpful. I think your suggestion allows me set references without manually removing and replacing all those references which took me about 30+ min to try and see if I could even run heck/chroma. I'll try that out!
I think your 3rd suggestion was to do this, but I still got the same error. Sorry this has devolved into tech support for me ha ha. I hope you are ok with that. Thanks.
```
CustomObstacleData customObsData = new CustomObstacleData(time, lineIndex,..., new CustomData(), true);

data.AddBeatmapObjectDataInOrder(customObsData)
```

**Comment by procedure1** [comment]
Sorry, I found that I had another statement... 
data.AddBeatmapObjectDataInOrder(new ObstacleData(...
that I didn't change out as per your suggestion. So it looks like everything is fixed now. Thanks so much!
