### ISSUE TITLE
2.7.16/1.5.16 followup: 'Storyteller' still broken.

### ISSUE THREAD

**Issue by Xentha** [Aeroluna/Heck#99]
So, yay, Transition light events do now work, thank you so so much for that, I'm so happy to see the map I used them in back to normal.

However for sake of reporting this lingering issue; the map Storyteller (bsr 2c40b) is still broken.
I'm not entirely sure if this is a chroma or a noodle issue, and I don't know what function is being used that doesn't work, but it significantly affects at least two specific scenes.
The light beams in scene 1, are missing, the cube walls in the fourth scene (by far my favorite) are missing, leaving the entire scene blank.
Some other scenes have incorrect lighting, but that's less relevant.

Here's a picture showing the difference in the scenes between 1.27 and 1.29.1..
![ggadd](https://github.com/Aeroluna/Heck/assets/75454177/7a8d8675-1c86-4d94-b547-95d43ded8de2)

**Comment by Aeroluna** [comment]
![image](https://github.com/Aeroluna/Heck/assets/40481393/0186e117-35f0-47ce-84d2-71b1921204ed)
![image](https://github.com/Aeroluna/Heck/assets/40481393/115cdc10-3964-4be8-83fa-ed320a3a5d07)

The difference is caused by refactors to the point system that caused reading points to be more strict.
Previous behavior where faulty points were still loaded will not be reinstated, it is up to the mapper to fix their maps.
